### ISSUE TITLE
Feature Request: Attachments

### ISSUE THREAD

**Issue by esolitos** [cyli/logstash-output-slack#7]
Is there any plan to support this in the future?

**Comment by cyli** [comment]
@esolitos: I originally added it here:  https://github.com/cyli/logstash-output-slack/commit/1ee255950b1bc1381fbdf961e9f4c40999336c86, but then removed it https://github.com/cyli/logstash-output-slack/commit/15b6e6d28ee3af813b4a584db7e958e46b0486ce because I wasn't sure where the attachments would come from (also I probably did it wrong).

Did you want it to come from the log event itself?

**Comment by esolitos** [comment]
Hi @cyli, yes i think that getting them from the entry being processed is the right assumption, wherelse were you thinking?
It's always possible to set some defaults in the output config, right?

The code you used seems fine to me, just set it as array and deliver what has been put in it.

**Comment by cyli** [comment]
@esolitos Sorry for the delay, I was on vacation.  Would you mind having a look at the PR and in particular see the event "attachments" field behavior (how it overrides the configured "attachments")  makes sense?  Thank you!

**Comment by esolitos** [comment]
Hello @cyli, absolutely no problem for the delay, I hope you had a nice vacation! :tropical_drink: :tropical_fish: 

I looked at the PR and it looks fine to me, simple enough and it does what's required. :+1: 

Is you really want you can add a test with multiple attachments? But, I mean.. It's just a detail. :)

**Comment by cyli** [comment]
@esolitos Thanks!  And yes, good point, thank you.  Will add test, merge, and release.
